language: node_js
node_js:
  - "node" # latest / current
  - "lts/*"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  - PGUSER=postgres PGDATABASE=travis_ci_test
